# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 608)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: #FFFFFF;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.create_desk_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_desk_button.sizePolicy().hasHeightForWidth())
        self.create_desk_button.setSizePolicy(sizePolicy)
        self.create_desk_button.setMinimumSize(QtCore.QSize(150, 0))
        self.create_desk_button.setStyleSheet("QPushButton{\n"
"                                background-color: transparent;\n"
"                                border: 1px outset rgb(220, 220, 220);\n"
"                                border-radius: 5px;\n"
"                                padding: 5px 10px 5px; \n"
"                            }\n"
"                            QPushButton:hover{\n"
"                                background-color:rgb(220, 220, 220);\n"
"                                border: 0px solid;\n"
"                                border-radius: 5px;\n"
"                                padding: 5px 10px 5px; \n"
"                            }\n"
"                            QPushButton:pressed{\n"
"                                background-color:rgb(200, 200, 200);\n"
"                                border: 0px solid;\n"
"                                border-radius: 5px;\n"
"                                padding: 5px 10px 5px; \n"
"                            }")
        self.create_desk_button.setObjectName("create_desk_button")
        self.verticalLayout.addWidget(self.create_desk_button)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.create_desk_button.setText(_translate("MainWindow", "Создать доску"))
